local module = {}

module.CharacterNames = {
	["Masculine"] = {
		"Andrew",
		"Aaron",
		"Anthony",
		"Blake",
		"Benjamin",
		"Bart",
		"Charlie",
		"Corey",
		"Connor",
		"Chris",
		"Dominic",
		"Derek",
		"David",
		"Dennis",
		"Edison",
		"Elliot",
		"Eric",
		"Francis",
		"Franklin",
		"Fabian",
		"Gustav",
		"Gibby",
		"Gabriel",
		"Hanz",
		"Hector",
		"Hank",
		"India",
		"Ian",
		"Isaac",
		"Jack",
		"John",
		"Jamal",
		"Juan",
		"James",
		"Kent",
		"Kyle",
		"Kobe",
	},
	
	["Feminine"] = {
		"Anna",
		"Arin",
		"Alice",
		"Becka",
		"Brittany",
		"Bridgette",
		"Cathy",
		"Christina",
		"Crystal",
		"Diana",
		"Daquesha",
		"Daniela",
		"Ella",
		"Emily",
		"Emery",
		"Elizabeth",
		"Farah",
		"Fantasia",
		"Fiona",
		"Giselle",
		"Gabby",
		"Gabriela",
		"Grace",
		"Hannah",
		"Helen",
		"India",
		"Isabella",
		"Ivy",
		"Juliet",
		"Jennfier",
		"Jenna",
		"Jacquie",
		"Jaoime",
		"Karen",
		"Kayla",
		"Kendra",
	},
}

module.SettingNames = {
	["Fantasy"] = {
		"The Underworld",
		"Babylon",
		"Medieval England",
		"Minecraft Nether",
		"Discord Moderator's DMs",
		"Roblox Crossroads",
		"Doomspire",
		"The Backrooms",
	},
	
	["Present"] = {
		"Ontario, Canada",
		"Vancouver, Canada",
		"Los Angeles, California",
		"Lincoln, Nebraska",
		"Tampa, Florida",
		"Long Island, New York",
		"Chicago, Illinois",
		"Mexico City, Mexico",
		"Rio de Janeiro, Brazil",
		"Sydney, Australia",
		"Kyiv, Ukraine",
		"London, United Kingdom",
		"Albuquerque, New Mexico",
		"Kandahar, Afghanistan",
		"Brooklyn, New York",
		"Kenosha, Wisconsin",
		"San Diego, California",
		"Greensboro, North Carolina",
		"Paris, France",
		"Pyongyang, North Korea",
		"Tokyo, Japan",
		"Seoul, South Korea",
		"Moscow, Russia",
		"Baghdad, Iraq",
		"Reykjavik, Iceland",
		"Chernobyl, Russia",
		
	},
	
	["Future"] = {
		"Planet Mars",
		"Space Station 31",
		"Space Station 105",
		"New Vegas",
		"USG Ishimura",
		"Metaverse",
		"Post-Apocalyptic Canada (USA)",
	},
}

module.JobNames = {
	["Combat"] = {
		"Marauder",
		"Soldier",
		"Sniper",
		"Medic",
		"Bandit",
		"Robber",
		"Military Pilot",
		"Special Forces",
		"Rebel"
	},
	
	["Regular"] = {
		"Doctor",
		"Professor",
		"Farmer",
		"Chef",
		"Scientist",
		"Engineer",
		"Technician",
		"Commercial Pilot",
	},
	
	["Influencer"] = {
		"Artist",
		"YouTuber",
		"Tiktoker",
		"Twitch Streamer",
		"Professional Gamer",
	},
	
	["Other"] = {
		"Unemployed",
		"Student",
		"Peasant",
		"Discord Moderator",
		"Explorer",
		"Hacker",
	},
}

return module
